server:
  port: 50000
  undertow:
    max-http-post-size: 100MB

spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
      # 设置文件缓存的临界点,超过则先保存到临时目录,默认为0,所有文件都会进行缓存
      file-size-threshold: 0
  application:
    name: calendar_sys
  jackson:
#    time-zone: GMT+8
#    date-format: yyyy-MM-dd HH:mm:ss
    # springboot响应json null值过滤
    default-property-inclusion: non_null
    generator:
      write_numbers_as_strings: true
  # 数据库
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.0.108:3306/sanitation-kitchen?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initialSize: 3
      max-active: 10
      max-wait: 50000
      keep-alive-between-time-millis: 50000
      keep-alive: false
  redis:
    database: 0
    host: 192.168.0.108
    port: 6379
    timeout: 5000
    password:

# sql 打印
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: deleted  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
gofastdfs:
  file:
    path: http://192.168.0.108:8089/
    group: group1
    host: http://192.168.0.108:8089

# 自定义配置
g780-data-package:
  # 标识位
  flag:
    index: 0
    size: 1
  # 数据头
  data-header:
    # 数据包类型
    type-index: 1
    type-size: 1
    # 数据包长度(但不包括数据体)
    length-index: 2
    length-size: 2
    # 设备号
    device-number-index: 4
    device-number-size: 11
    # 移动IP
    ip-index: 15
    ip-size: 4
    # 端口
    port-index: 19
    port-size: 2

id:
  datacenter-id: 1
  worker-id: 1
